export const memos = [
  {
    id: 'testing_id',
    author: 'DeoZ',
    timestamps: {
      created: '2023-01-01T00:00:00.277Z',
      updated: '2023-09-13T23:59:59.277Z',
    },
    title: 'Тестовая памятка',
    type: 'todo',
    category: { id: 'test_category', name: 'Test Category 1' },
    tagList: [
      { id: 'tag 1', label: 'tag 1' },
      { id: 'tag2', label: 'tag2' },
      { id: 'tag_3', label: 'tag_3' },
      { id: 'tag-4', label: 'tag-4' },
      { id: 'test tag tag tag tag tag test', label: 'test tag tag tag tag tag test' },
    ],
    list: [
      { id: 'id1', label: 'Item 1', checked: false },
      { id: 'id2', label: 'Item 2', checked: false },
      { id: 'id 3', label: 'Item 3', checked: true },
      { id: 'id 4', label: 'Item 456', checked: false },
      { id: 'id_5', label: 'Item Item Item Item Item Item Item Item Item', checked: false },
      { id: 'id-6', label: 'Testing Item', checked: false },
      { id: 'ID7', label: 'Test', checked: true },
    ],
    rating: { value: 123456, hasMark: true },
  },
  {
    id: 17,
    author: 'DeoZ',
    timestamps: {
      created: '2023-08-19T07:54:10.277Z',
      updated: '2023-09-04T18:12:37.277Z',
    },
    title: 'Взять в путешествие',
    type: 'todo',
    category: { id: 'category1', name: 'Взять с собой' },
    tags: [
      { id: 'путешествия', label: 'путешествия' },
      { id: 'море', label: 'море' },
      { id: 'отпуск', label: 'отпуск' },
      { id: 'отдых', label: 'отдых' },
      { id: 'не забыть', label: 'не забыть' },
      { id: 'поездка', label: 'поездка' },
      { id: 'в дорогу', label: 'в дорогу' },
      { id: 'чек-лист', label: 'чек-лист' },
    ],
    list: [
      { id: '1', label: 'Паспорт', checked: true },
      { id: '2', label: 'Билет', checked: false },
      { id: '3', label: 'Страховка', checked: false },
      { id: '4', label: 'Деньги и/или банковская карта', checked: false },
      { id: '5', label: 'Телефон', checked: false },
      { id: '6', label: 'Зарядка для телефона', checked: false },
      { id: '7', label: 'Аптечка', checked: false },
      { id: '8', label: 'Камера', checked: false },
      { id: '9', label: 'Носки и трусы', checked: true },
      { id: '10', label: 'Футболки', checked: false },
      { id: '11', label: 'Джинсы и брюки', checked: false },
      { id: '12', label: 'Шлёпанцы', checked: false },
    ],
    rating: { value: 182, hasMark: false },
  },
  {
    id: 'as9d1dokoasd91ujdj13d8312fd',
    author: 'Алексей Денисов',
    timestamps: {
      created: '2023-09-13T10:12:38.517Z',
    },
    title: 'Достопримечательности Дубая',
    type: 'todo',
    category: { id: 'dostoprimechatelnosti-1', name: 'Достопримечательности' },
    tags: [
      { id: 'достопримечательности', label: 'достопримечательности' },
      { id: 'Дубай', label: 'Дубай' },
      { id: 'ОАЭ', label: 'ОАЭ' },
      { id: 'поездки', label: 'поездки' },
      { id: 'путешествия', label: 'путешествия' },
      { id: 'чек-лист', label: 'чек-лист' },
      { id: 'красивые места', label: 'красивые места' },
      { id: 'нужно сделать', label: 'нужно сделать' },
    ],
    list: [
      { id: '1', label: 'Бурдж-Халифа', checked: true },
      { id: '2', label: 'Поющие фонтаны', checked: false },
      { id: '3', label: 'Дубай Молл и аквариум', checked: false },
      { id: '4', label: 'Отель Парус (Бурдж Аль-Араб)', checked: false },
      { id: '5', label: 'Пляж Джумейра', checked: false },
      { id: '6', label: 'Молл Эмиратов и горнолыжный комплекс «Ски Дубай»', checked: false },
      { id: '7', label: 'Дубайская Рамка', checked: false },
      { id: '8', label: 'Район Дейра', checked: false },
      { id: '9', label: 'Рынок специй', checked: false },
      { id: '10', label: 'Золотой рынок', checked: false },
      { id: '11', label: 'Пальма Джумейра и Курортный комплекс Atlantis The Palm', checked: false },
      { id: '12', label: 'Смотровая площадка The View at The Palm', checked: false },
      { id: '13', label: 'Бассейн Aura Skypool', checked: false },
      { id: '14', label: 'Фонтан The Palm Fountain', checked: false },
      { id: '15', label: 'Залив Дубай-Крик', checked: false },
      { id: '16', label: 'Район Бастакия (Аль-Фахиди)', checked: false },
      { id: '17', label: 'Форт Аль-Фахиди и Музей Дубая', checked: false },
      { id: '18', label: 'Аквапарк Wild Wadi', checked: false },
      { id: '19', label: 'Мечеть Джумейра', checked: false },
      { id: '20', label: 'Озеро Любви', checked: false },
      { id: '21', label: 'Парк Motiongate', checked: false },
      { id: '22', label: 'Парк BollywoodParks Dubai', checked: false },
      { id: '23', label: 'Парк развлечений Legoland', checked: false },
      { id: '24', label: 'Парк развлечений IMG Worlds of Adventure', checked: false },
      { id: '25', label: 'Мадинат Джумейра', checked: false },
      { id: '26', label: 'Пляж Кайт-Бич', checked: false },
      { id: '27', label: 'Музей Этихад', checked: false },
      { id: '28', label: 'Аквапарк Aquaventure', checked: false },
      { id: '29', label: 'Деревня наследия', checked: false },
      { id: '30', label: 'Дубайский оперный театр', checked: false },
      { id: '31', label: 'Район Дубай Марина и пляж', checked: false },
      { id: '32', label: 'Шоссе Шейха Зайда', checked: false },
      { id: '33', label: 'Музей будущего', checked: false },
      { id: '34', label: 'Парк цветов Dubai Miracle Garden (Сад чудес)', checked: false },
      { id: '35', label: 'Светящийся сад Dubai Garden Glow', checked: false },
      { id: '36', label: 'Выставка Global Village', checked: false },
      { id: '37', label: 'Колесо обозрения Ain Dubai', checked: false },
      { id: '38', label: 'Дубайский пустынный заповедник', checked: false },
    ],
    rating: { value: 0, hasMark: false },
  },
];
